version: "3.8"
services:
  backend:
    build: ./backend
    container_name: cf_back
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    container_name: cf_front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
